# Generated by Django 3.2.3 on 2021-05-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60, verbose_name="title")),
                ("created", models.DateField(auto_now=True, verbose_name="created on")),
                ("length", models.CharField(max_length=20, verbose_name="length")),
                (
                    "actors",
                    models.ManyToManyField(
                        blank=True, to="actors.Actor", verbose_name="actors"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Commercial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60, verbose_name="title")),
                ("created", models.DateField(auto_now=True, verbose_name="created on")),
                ("company", models.CharField(max_length=60, verbose_name="company")),
                (
                    "actors",
                    models.ManyToManyField(
                        blank=True, to="actors.Actor", verbose_name="actors"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
