# Generated by Django 3.1.5 on 2021-02-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('created', models.DateField(auto_now=True, verbose_name='created on')),
                ('length', models.CharField(max_length=200, verbose_name='length')),
                ('actors', models.ManyToManyField(blank=True, to='actors.Actor', verbose_name='actors')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('created', models.DateField(auto_now=True, verbose_name='created on')),
                ('company', models.CharField(max_length=200, verbose_name='company')),
                ('actors', models.ManyToManyField(blank=True, to='actors.Actor', verbose_name='actors')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
