# Generated by Django 3.1.5 on 2021-02-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210201_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='company',
            field=models.CharField(max_length=60, verbose_name='company'),
        ),
    ]
